# Generated by Django 3.2.25 on 2024-09-16 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20211006_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.device'),
        ),
    ]
